modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
[[mods]]
    modId="voltutils"
    license="MIT License"
    version="1.0"
    displayName="Voltwork: Utils"
    issueTrackerURL="https://github.com/ModdedMCStudios/VoltworkUtils/issues"
    #displayURL="nourlyet"
    logoFile="logo.png"
    authors="Modded MC Studios"
    credits="Jerome226, minemobs, Unhooking."
    description='''A mod for the Voltwork modpack.'''

[[dependencies.superpackutils]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.superpackutils]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.superpackutils]]
    modId="mekanism"
    mandatory=true
    versionRange="[1.16.4-10.0.18.445,)"
    ordering="NONE"
    side="BOTH"
